cloud:
  aws:
    credentials:
      access-key: AKIA6PFTNSRPIPYYADPN
      secret-key: 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
    region:
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: s3-upload-and-download