cloud:
  aws:
    credentials:
      access-key: <Replace with you access key>
      secret-key: <Replace with you secret key>
    region:
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: s3-upload-and-download
